name: Contracts

on:
  workflow_call:

jobs:
  contracts:
    name: Forge build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1

      - name: Install Solidity dependencies
        working-directory: packages/contracts
        run: forge soldeer install

      - name: Build contracts
        working-directory: packages/contracts
        run: forge build

      - name: Test contracts
        working-directory: packages/contracts
        run: forge test -v
